import React from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { Info, AlertTriangle, CheckCircle, ExternalLink, Monitor, Volume2, FileText, Image } from 'lucide-react';
import Button from '../components/common/Button';
import { useTheme } from '../contexts/ThemeContext';

const EducationalPage: React.FC = () => {
  const { theme } = useTheme();
  const navigate = useNavigate();
  
  const fadeInUp = {
    hidden: { opacity: 0, y: 20 },
    visible: { 
      opacity: 1, 
      y: 0,
      transition: {
        duration: 0.5
      }
    }
  };
  
  const staggerContainer = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.2
      }
    }
  };
  
  return (
    <div className="max-w-4xl mx-auto">
      <motion.div
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
      >
        <div className="text-center mb-10">
          <h1 className="text-3xl md:text-4xl font-bold mb-4">Deepfake Education Center</h1>
          <p className="text-lg max-w-3xl mx-auto">
            Learn how to identify manipulated media and protect yourself from deepfakes with our comprehensive educational resources.
          </p>
        </div>
        
        {/* Introduction Section */}
        <section className={`mb-12 p-8 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}>
          <div className="flex flex-col md:flex-row items-start gap-6">
            <div className="md:w-2/3">
              <h2 className="text-2xl font-bold mb-4">What are Deepfakes?</h2>
              <p className="mb-4">
                Deepfakes are synthetic media where a person's likeness is replaced with someone else's using artificial intelligence. 
                They can appear in various forms including images, videos, audio, and text.
              </p>
              <p className="mb-4">
                As AI technology advances, these manipulations are becoming increasingly sophisticated and difficult to detect with the naked eye. 
                Understanding how to identify potential deepfakes is becoming an essential digital literacy skill.
              </p>
              <div className="flex mt-4">
                <Button 
                  size="sm" 
                  onClick={() => window.open('https://www.youtube.com/watch?v=dMF2i3A9Lzw', '_blank')}
                  icon={<ExternalLink className="h-4 w-4" />}
                >
                  Watch Explainer Video
                </Button>
              </div>
            </div>
            <div className="md:w-1/3 flex-shrink-0">
              <div className="relative h-48 rounded-lg overflow-hidden">
                <img 
                  src="https://images.pexels.com/photos/2599244/pexels-photo-2599244.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=2" 
                  alt="AI concept illustration"
                  className="w-full h-full object-cover"
                />
                <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent flex items-end p-4">
                  <div className="text-white text-xs">
                    The boundary between real and fake is increasingly blurred
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
        
        {/* Types of Deepfakes */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Types of Deepfakes</h2>
          
          <motion.div 
            className="grid grid-cols-1 md:grid-cols-2 gap-6"
            variants={staggerContainer}
            initial="hidden"
            animate="visible"
          >
            <motion.div 
              className={`p-6 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}
              variants={fadeInUp}
            >
              <div className="flex items-center mb-4">
                <div className={`p-3 rounded-full ${theme === 'dark' ? 'bg-purple-900' : 'bg-purple-100'}`}>
                  <Image className={`h-6 w-6 ${theme === 'dark' ? 'text-purple-300' : 'text-purple-600'}`} />
                </div>
                <h3 className="text-xl font-semibold ml-3">Image Deepfakes</h3>
              </div>
              <p className="mb-4">
                Manipulated photos where faces are swapped or entire images are generated by AI. Common in fake profiles and misinformation campaigns.
              </p>
              <ul className="list-disc list-inside space-y-2 mb-4">
                <li>Face swapping</li>
                <li>Attribute manipulation (age, gender, etc.)</li>
                <li>Completely AI-generated people</li>
                <li>Background/context manipulation</li>
              </ul>
              <Button 
                variant="outline" 
                size="sm" 
                onClick={() => navigate('/scan/image')}
              >
                Analyze Images
              </Button>
            </motion.div>
            
            <motion.div 
              className={`p-6 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}
              variants={fadeInUp}
            >
              <div className="flex items-center mb-4">
                <div className={`p-3 rounded-full ${theme === 'dark' ? 'bg-blue-900' : 'bg-blue-100'}`}>
                  <Monitor className={`h-6 w-6 ${theme === 'dark' ? 'text-blue-300' : 'text-blue-600'}`} />
                </div>
                <h3 className="text-xl font-semibold ml-3">Video Deepfakes</h3>
              </div>
              <p className="mb-4">
                Videos where a person's face or voice is replaced with someone else's. Often used to create fake celebrity content or political misinformation.
              </p>
              <ul className="list-disc list-inside space-y-2 mb-4">
                <li>Face replacement in videos</li>
                <li>Lip-sync manipulation</li>
                <li>Body movement manipulation</li>
                <li>Synthetic scenes</li>
              </ul>
              <Button 
                variant="outline" 
                size="sm" 
                onClick={() => navigate('/scan/video')}
              >
                Analyze Videos
              </Button>
            </motion.div>
            
            <motion.div 
              className={`p-6 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}
              variants={fadeInUp}
            >
              <div className="flex items-center mb-4">
                <div className={`p-3 rounded-full ${theme === 'dark' ? 'bg-green-900' : 'bg-green-100'}`}>
                  <Volume2 className={`h-6 w-6 ${theme === 'dark' ? 'text-green-300' : 'text-green-600'}`} />
                </div>
                <h3 className="text-xl font-semibold ml-3">Audio Deepfakes</h3>
              </div>
              <p className="mb-4">
                Synthetic voice cloning that mimics a person's speech patterns and tone. Can be used for scams or impersonation.
              </p>
              <ul className="list-disc list-inside space-y-2 mb-4">
                <li>Voice cloning and synthesis</li>
                <li>Accent and emotion manipulation</li>
                <li>Content generation with existing voice</li>
                <li>Audio-splicing and manipulation</li>
              </ul>
              <Button 
                variant="outline" 
                size="sm" 
                onClick={() => navigate('/scan/audio')}
              >
                Analyze Audio
              </Button>
            </motion.div>
            
            <motion.div 
              className={`p-6 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}
              variants={fadeInUp}
            >
              <div className="flex items-center mb-4">
                <div className={`p-3 rounded-full ${theme === 'dark' ? 'bg-amber-900' : 'bg-amber-100'}`}>
                  <FileText className={`h-6 w-6 ${theme === 'dark' ? 'text-amber-300' : 'text-amber-600'}`} />
                </div>
                <h3 className="text-xl font-semibold ml-3">Text Deepfakes</h3>
              </div>
              <p className="mb-4">
                AI-generated text that mimics human writing styles. Used to create fake news articles, social media posts, or impersonate writing styles.
              </p>
              <ul className="list-disc list-inside space-y-2 mb-4">
                <li>Style mimicry and impersonation</li>
                <li>Automated content generation</li>
                <li>Fake news and misinformation</li>
                <li>Social engineering attacks</li>
              </ul>
              <Button 
                variant="outline" 
                size="sm" 
                onClick={() => navigate('/scan/text')}
              >
                Analyze Text
              </Button>
            </motion.div>
          </motion.div>
        </section>
        
        {/* How to Spot Deepfakes */}
        <section className="mb-12">
          <div className="flex items-center mb-6">
            <h2 className="text-2xl font-bold">How to Spot Deepfakes</h2>
            <div className={`ml-4 px-3 py-1 text-xs rounded-full ${
              theme === 'dark' ? 'bg-indigo-900 text-indigo-200' : 'bg-indigo-100 text-indigo-800'
            }`}>
              Essential Skills
            </div>
          </div>
          
          <div className={`p-6 rounded-lg shadow-md mb-8 ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <div>
                <h3 className="flex items-center text-xl font-semibold mb-4">
                  <AlertTriangle className={`h-5 w-5 mr-2 ${theme === 'dark' ? 'text-red-400' : 'text-red-500'}`} />
                  Visual Clues in Images & Videos
                </h3>
                <ul className="space-y-3">
                  {[
                    "Look for unnatural blinking or lack of blinking",
                    "Check for inconsistent lighting and shadows",
                    "Examine facial boundaries for blurring or artifacts",
                    "Note any unnatural skin textures or color inconsistencies",
                    "Pay attention to strange teeth or eye reflections",
                    "Watch for unnatural head movements or positions"
                  ].map((item, index) => (
                    <li key={index} className="flex items-start">
                      <span className={`inline-block w-5 h-5 rounded-full mr-2 mt-0.5 flex-shrink-0 ${
                        theme === 'dark' ? 'bg-red-900 text-red-200' : 'bg-red-100 text-red-800'
                      } text-xs flex items-center justify-center`}>
                        {index + 1}
                      </span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
              
              <div>
                <h3 className="flex items-center text-xl font-semibold mb-4">
                  <AlertTriangle className={`h-5 w-5 mr-2 ${theme === 'dark' ? 'text-yellow-400' : 'text-yellow-500'}`} />
                  Audio & Text Warning Signs
                </h3>
                <ul className="space-y-3">
                  {[
                    "Listen for unnatural breathing patterns or pauses",
                    "Check for inconsistent voice tone or emotion",
                    "Look for repetitive language patterns in text",
                    "Note context inconsistencies or knowledge gaps",
                    "Be suspicious of unusual phrasing or vocabulary",
                    "Verify information through multiple reliable sources"
                  ].map((item, index) => (
                    <li key={index} className="flex items-start">
                      <span className={`inline-block w-5 h-5 rounded-full mr-2 mt-0.5 flex-shrink-0 ${
                        theme === 'dark' ? 'bg-yellow-900 text-yellow-200' : 'bg-yellow-100 text-yellow-800'
                      } text-xs flex items-center justify-center`}>
                        {index + 1}
                      </span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className={`p-6 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}>
              <div className="flex items-center mb-4">
                <CheckCircle className={`h-6 w-6 mr-2 ${theme === 'dark' ? 'text-green-400' : 'text-green-500'}`} />
                <h3 className="text-lg font-semibold">Verification Tools</h3>
              </div>
              <p className="mb-4">
                Use reputable fact-checking websites and deepfake detection tools like DeepScan AI to help verify content authenticity.
              </p>
              <Button 
                variant="outline" 
                size="sm" 
                fullWidth
                onClick={() => navigate('/scan/image')}
              >
                Try Our Detection Tool
              </Button>
            </div>
            
            <div className={`p-6 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}>
              <div className="flex items-center mb-4">
                <Info className={`h-6 w-6 mr-2 ${theme === 'dark' ? 'text-blue-400' : 'text-blue-500'}`} />
                <h3 className="text-lg font-semibold">Source Checking</h3>
              </div>
              <p className="mb-4">
                Always verify the original source of media before sharing. Check if reputable news organizations have reported the same information.
              </p>
              <ul className="list-disc list-inside text-sm">
                <li>Check multiple sources</li>
                <li>Verify timestamps and context</li>
                <li>Research the original publisher</li>
              </ul>
            </div>
            
            <div className={`p-6 rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}>
              <div className="flex items-center mb-4">
                <AlertTriangle className={`h-6 w-6 mr-2 ${theme === 'dark' ? 'text-amber-400' : 'text-amber-500'}`} />
                <h3 className="text-lg font-semibold">Critical Thinking</h3>
              </div>
              <p className="mb-4">
                Develop a healthy skepticism about sensational content, especially if it seems designed to provoke strong emotional reactions.
              </p>
              <ul className="list-disc list-inside text-sm">
                <li>Question emotional content</li>
                <li>Consider who benefits</li>
                <li>Evaluate if claims make sense</li>
              </ul>
            </div>
          </div>
        </section>
        
        {/* Resources Section */}
        <section className={`mb-12 p-8 rounded-lg shadow-md ${
          theme === 'dark' ? 'bg-indigo-900/30' : 'bg-indigo-50'
        }`}>
          <h2 className="text-2xl font-bold mb-6">Additional Resources</h2>
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-6">
            <div>
              <h3 className="text-lg font-semibold mb-3">Educational Materials</h3>
              <ul className="space-y-2">
                {[
                  { name: "Deepfake Detection Challenge", url: "#" },
                  { name: "Media Literacy 101", url: "#" },
                  { name: "AI Ethics Foundation", url: "#" },
                  { name: "Digital Citizenship Course", url: "#" },
                ].map((resource, index) => (
                  <li key={index}>
                    <a 
                      href={resource.url}
                      className="flex items-center group"
                    >
                      <ExternalLink className="h-4 w-4 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                      <span className="text-indigo-600 dark:text-indigo-300 hover:underline">
                        {resource.name}
                      </span>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
            
            <div>
              <h3 className="text-lg font-semibold mb-3">Trusted Verification Sites</h3>
              <ul className="space-y-2">
                {[
                  { name: "Fact Check Explorer", url: "#" },
                  { name: "Media Bias/Fact Check", url: "#" },
                  { name: "Snopes", url: "#" },
                  { name: "PolitiFact", url: "#" },
                ].map((resource, index) => (
                  <li key={index}>
                    <a 
                      href={resource.url}
                      className="flex items-center group"
                    >
                      <ExternalLink className="h-4 w-4 mr-2 opacity-0 group-hover:opacity-100 transition-opacity" />
                      <span className="text-indigo-600 dark:text-indigo-300 hover:underline">
                        {resource.name}
                      </span>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </section>
        
        {/* FAQ Section */}
        <section className="mb-12">
          <h2 className="text-2xl font-bold mb-6">Frequently Asked Questions</h2>
          
          <div className="space-y-4">
            {[
              {
                question: "How accurate are deepfake detection tools?",
                answer: "Current deepfake detection tools can achieve 65-90% accuracy depending on the type of media and the sophistication of the fake. Our DeepScan AI tool is constantly improving through machine learning and user feedback. However, no detection system is perfect, which is why combining automated tools with human verification and critical thinking is the best approach."
              },
              {
                question: "Are all AI-generated images considered deepfakes?",
                answer: "Not all AI-generated images are considered deepfakes in the harmful sense. The term 'deepfake' typically refers to AI-generated content that is intended to deceive. AI-generated art or clearly labeled AI content created for entertainment, art, or legitimate purposes wouldn't be classified as harmful deepfakes, though they use similar technology."
              },
              {
                question: "What should I do if I identify a deepfake?",
                answer: "If you identify a deepfake, consider: 1) Not sharing or amplifying it, 2) Reporting it to the platform where you found it, 3) Informing the person being impersonated if possible, 4) Sharing correct information from reliable sources if the deepfake is spreading misinformation, and 5) Using DeepScan AI to analyze and document the manipulation."
              },
              {
                question: "How can I protect myself from being used in deepfakes?",
                answer: "While you can't completely prevent your likeness from being used in deepfakes, you can: 1) Limit public photos and videos of yourself online, 2) Use privacy settings on social media, 3) Regularly search for your name online, 4) Be cautious about apps that require extensive personal data or facial scans, and 5) Support legislation and policies that address deepfake creation and distribution."
              },
            ].map((faq, index) => (
              <details 
                key={index}
                className={`group rounded-lg shadow-md ${theme === 'dark' ? 'bg-gray-800' : 'bg-white'}`}
              >
                <summary className="flex justify-between items-center p-6 cursor-pointer list-none">
                  <h3 className="text-lg font-medium">{faq.question}</h3>
                  <div className="w-5 h-5 border-2 rounded-full border-indigo-500 flex items-center justify-center group-open:bg-indigo-500 transition-colors">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="w-3 h-3 group-open:rotate-180 transition-transform group-open:text-white"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
                    </svg>
                  </div>
                </summary>
                <div className="p-6 pt-0">
                  <p>{faq.answer}</p>
                </div>
              </details>
            ))}
          </div>
        </section>
        
        {/* Call to Action */}
        <section className={`p-8 rounded-lg shadow-md text-center ${theme === 'dark' ? 'bg-indigo-900' : 'bg-indigo-600'} text-white`}>
          <h2 className="text-2xl font-bold mb-4">Ready to Start Detecting Deepfakes?</h2>
          <p className="mb-6 max-w-2xl mx-auto">
            Put your knowledge to work by using our AI-powered detection tools to analyze suspicious content.
          </p>
          <div className="flex flex-col sm:flex-row justify-center gap-4">
            <Button 
              variant="secondary"
              size="lg"
              onClick={() => navigate('/scan/image')}
            >
              Scan Media Now
            </Button>
            <Button 
              variant="outline"
              size="lg"
              onClick={() => navigate('/dashboard')}
              className="bg-transparent border-white text-white hover:bg-white/10"
            >
              View Your Dashboard
            </Button>
          </div>
        </section>
      </motion.div>
    </div>
  );
};

export default EducationalPage;